name: helloworld_1
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  # sdk: ' >=2.17.0 <3.0.0'
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^1.10.0
  test: ^1.16.0
